### ISSUE TITLE
Offer for further development to Thunderbird 60.2.1

### ISSUE THREAD

**Issue by jabommi** [arima-ryunosuke/redthunderminebird#1]
Dear Mr. Ryunosuke,

we have been using Redmine and Thunderbird for years now and it would make our work a lot easier if your Redmine plugin would be available for the current Thunderbird version 60.2.1 (64-bit) in english.

Therefore, we would kindly ask you to contact us and let us know what it would cost to make the plugin a) compatible with the above version and b) available in english.

You can contact us via E-Mail: technik(AT)jabommi(DOT)de

Respectfully

Jan Hennschen
CEO JABOMMI GmbH

**Comment by arima-ryunosuke** [comment]
@jabommi

Hello, thank you for using this addon.

The latest version passes the Mozilla examination on 5/20.
Please see https://addons.thunderbird.net/addon/redmine%E9%80%A3%E6%90%BA/
